# Copyright 2018 Owkin, inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
apiVersion: skaffold/v1beta13
kind: Config


deploy:
  statusCheckDeadlineSeconds: 300
  helm:
    releases:
      - name: orderer1
        chartPath: charts/hlf-k8s
        namespace: orderer
        valuesFiles: [examples/2-orgs-policy-any/values/orderer1.yaml]
        imageStrategy:
          helm: {}
      - name: orderer2
        chartPath: charts/hlf-k8s
        namespace: orderer
        valuesFiles: [examples/2-orgs-policy-any/values/orderer2.yaml]
        imageStrategy:
          helm: {}
      - name: orderer3
        chartPath: charts/hlf-k8s
        namespace: orderer
        valuesFiles: [examples/2-orgs-policy-any/values/orderer3.yaml]
        imageStrategy:
          helm: {}



      - name: org-1-peer-1
        chartPath: charts/hlf-k8s
        namespace: org-1
        valuesFiles: [examples/2-orgs-policy-any/values/org-1-peer-1.yaml]
        imageStrategy:
          helm: {}
  
      - name: org-2-peer-1
        chartPath: charts/hlf-k8s
        namespace: org-2
        valuesFiles: [examples/2-orgs-policy-any/values/org-2-peer-1.yaml]
        imageStrategy:
          helm: {}

      # - name: network-org-2-peer-1
      #   chartPath: charts/hlf-k8s
      #   namespace: org-2
      #   valuesFiles: [examples/2-orgs-policy-any/values/org-2-peer-1.yaml]
      #   imageStrategy:
      #     helm: {}
      #   values:
      #     fabric-tools.image: substrafoundation/fabric-tools
      #     hlf-peer.image: substrafoundation/fabric-peer

    # flags:
    #   install: ["--create-namespace"]


  # kubectl:
  #   manifests:
  #     # - examples/secrets/secrets-orderer-genesis.yaml
  #     # - examples/secrets/secrets-orderer.yaml
  #     # - examples/secrets/secrets-org-1.yaml
  #     # - examples/secrets/secrets-org-2.yaml
  #     # For chaincode secrets deletion
  #     - examples/serviceAccounts/serviceAccount-org-1.yaml
      # - examples/serviceAccounts/serviceAccount-org-2.yaml
