---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: substra-delete-hook
  namespace: orderer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: substra-delete-hook
  namespace: orderer
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs:
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: substra-delete-hook
  namespace: orderer
subjects:
  - kind: ServiceAccount
    name: substra-delete-hook
    namespace: orderer
roleRef:
  kind: Role
  name: substra-delete-hook
  apiGroup: rbac.authorization.k8s.io
