{{- if .Values.configOperator.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "substra.fullname" . }}-config-operator
  labels:
    app.kubernetes.io/name: {{ template "substra.fullname" . }}-config-operator
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with .Values.configOperator.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.configOperator.ingress.tls }}
  tls:
  {{- range .Values.configOperator.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  ingressClassName: {{ .Values.configOperator.ingress.ingressClassName }}
  rules:
  {{- range  .Values.configOperator.ingress.hosts  }}
    {{- $pathType := .pathType }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ template "substra.fullname" $ }}-config-operator
                port:
                  name: http
        {{- end }}
  {{- end }}
{{- end }}
---