{{- range $channel := .Values.appChannels }}
{{- if .ingress }}
{{- if .ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "substra.fullname" $ }}-appchannel-operator-{{ $channel.channelName }}
  labels:
    app.kubernetes.io/name: {{ template "substra.fullname" $ }}-appchannel-operator-{{ $channel.channelName }}
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
  {{- with .ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .ingress.tls }}
  tls:
  {{- range .ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  ingressClassName: {{ .ingress.ingressClassName }}
  rules:
  {{- range .ingress.hosts  }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ template "substra.fullname" $ }}-appchannel-operator-{{ $channel.channelName }}
                port:
                  name: http
        {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
